version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.9
    commands:
      - export PROJ_LOC=$(pwd)
      - pip install -r requirements.txt
      - npm -g i aws-cdk-lib
      - npm -g update                                                    
  build:
    commands:
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackCommonStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/DeciderLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/TriggerStateMachineLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/PrepareDataRetrieveFromDynamoDBLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/PrepareDataSaveToDynamoDBLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/BindRatioLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/SaveAndRetrieveFromDynamoDBLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ReportCSVLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ReportTriggerStateMachineLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/TransactionReportLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/AggregateReportLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ExpenseReportLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/StreamDataToS3LambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackCostDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackAuditLoggerDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ReadingFromDynamoDBStreamsLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/Kinesis --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ReadingFromKinesisLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/S3 --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackStepFunctionStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackReportStepFunctionStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackAthenaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackApigatewayStack --require-approval never

       
      
      