version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.9
    commands:
      - export PROJ_LOC=$(pwd)
      - pip install -r requirements.txt
      - npm -g i aws-cdk-lib
      - npm -g update                                                    
  build:
    commands:
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackCommonStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/DeciderLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/TriggerStateMachineLambdaStack --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/PrepareDataRetrieveFromDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/PrepareDataSaveToDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/SaveAndRetrieveFromDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/StreamDataToS3 --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/CertificateManager --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackCostDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/ChargebackAuditLoggerDynamoDB --require-approval never
      - npx cdk deploy ChargebackPipelineStack/development/S3 --require-approval never
      
      