version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.9
    commands:
      - export PROJ_LOC=$(pwd)
      - pip install -r requirements.txt
      - npm -g i aws-cdk-lib
      - npm -g update
  build:
    commands:
      - npx cdk deploy ChargebackPipelineStack --require-approval never
     
                                                                              