version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - npm install -g aws-cdk && pip install -r requirements.txt
  build:
    commands:
      - cd test
      - pytest
environment:
  buildImage: LinuxBuildImage.STANDARD_5_0
  privileged: True